name = "worker-signed-s3-template"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.dev]
vars = { AWS_ACCESS_KEY_ID = "", AWS_SECRET_ACCESS_KEY = "", AWS_DEFAULT_REGION = "", AWS_S3_BUCKET = ""}
